version: 2.1
jobs:
  build:
    macos:
      xcode: "10.0.0"
    steps:
    - checkout
    - sonar/scan:
        os: macosx
        sonar_token_variable_name: SONAR_TOKEN2
orbs:
  sonar: sonarsource/sonarcloud@dev:alpha
workflows:
  version: 2
  main:
    jobs:
      - build:
          context: sonarcloud




