version: 2.1
jobs:
  build:
    docker:
      - image: 'node:latest'
    steps:
    - checkout
    - sonar/analyze
orbs:
  sonar: tom-vanbraband-sns/scanner-no-docker@dev:0.0.29
workflows:
  version: 2
  main:
    jobs:
      - build:
          context: test



