version: 2.1
jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
orbs:
  sonar: sonarsource/sonarcloud@dev:orb2.0
workflows:
  main:
    jobs:
      - build
      - sonar/scan:
          context: sonarcloud
          requires: 
            - build



