version: 2.1

jobs:
  hello-node:
    executor: hello-orb/default
    steps:
      - hello-orb/show-version
  hello-not-node:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Hello World
          command: |
            node -v
orbs:
  hello-orb: tom-vanbraband-sns/hello-world@dev:0.0.3

workflows:
  hello-workflow:
    jobs:
      - hello-node
      - hello-not-node:
          requires: 
            - hello-node