version: 2.1
jobs:
  build:
    macos:
      xcode: "9.0"
    steps:
    - checkout
    - sonar/analyze:
        os: macosx
orbs:
  sonar: tom-vanbraband-sns/scanner-no-docker@dev:0.0.25
workflows:
  version: 2
  main:
    jobs:
      - build:
          context: test

