version: 2.1
jobs:
  build:
    docker:
      - image: node:latest
    steps:
    - checkout
    - sonar/scan:
        os: macosx
orbs:
  sonar: sonarsource/sonarcloud@dev:alpha
workflows:
  version: 2
  main:
    jobs:
      - build:
          context: sonarcloud