version: 2.1

jobs:
  build:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@dev

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud


