version: 2.1

jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - sonarcloud/scan:
          cache_version: 15445844554

orbs:
  sonarcloud: sonarsource/sonarcloud@dev:alpha-dogfood

workflows:
  main:
    jobs:
      - build:
          context: sonarcloud






