version: 2.1

jobs:
  build:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - sonarcloud/scan:
          project_root: 'sub-project'

orbs:
  sonarcloud: sonarsource/sonarcloud@dev:alpha
  

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud


