version: 2.1
jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - sonar/scan:
orbs:
  sonar: sonarsource/sonarcloud@dev:alpha-ngrok
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud
