version: 2.1
jobs:
  build:
    executor: sonar/default
    steps:
    - checkout
    - sonar/analyze
orbs:
  sonar: tom-vanbraband-sns/sonarcloud@dev:0.0.9
workflows:
  version: 2
  main:
    jobs:
      - build:
          context: test