version: 2.1
jobs:
  build:
    macos:
      xcode: "10.0.0"
    steps:
    - checkout
    - sonar/analyze:
        os: macosx
orbs:
  sonar: sonarsource/sonarcloud@dev:alpha
workflows:
  version: 2
  main:
    jobs:
      - build:
          context: test



