version: 2.1
jobs:
  build:
    docker:
      - image: python:latest
    steps:
    - checkout
    - sonar/scan:
        cache_version: 2
orbs:
  sonar: sonarsource/sonarcloud@dev:alpha
workflows:
  version: 2
  main:
    jobs:
      - build:
          context: sonarcloud
